// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BouQVEu6J1HGWi7_91Y9v_8LUCnIBBg',
    appId: '1:274141820242:web:562bacd75596177f49768b',
    messagingSenderId: '274141820242',
    projectId: 'makerere-app',
    authDomain: 'makerere-app.firebaseapp.com',
    storageBucket: 'makerere-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKAj9Li_j5g83YsQr8EoB9aRp9ftqho3g',
    appId: '1:274141820242:android:27eda1b85987618f49768b',
    messagingSenderId: '274141820242',
    projectId: 'makerere-app',
    storageBucket: 'makerere-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCth-wQZtk0bsAsHR1DKqJuwmKGXz55zDg',
    appId: '1:274141820242:ios:270577bd2088d31249768b',
    messagingSenderId: '274141820242',
    projectId: 'makerere-app',
    storageBucket: 'makerere-app.firebasestorage.app',
    iosBundleId: 'com.example.makerereDashboard',
  );
}
